### PR TITLE
Use BinaryProvider.jl

### LINKED ISSUE #12: Windows support
Any chance for Windows support? I assume it would require building snappy on opensuse and then using WinRPM to install, right?

### PR DESCRIPTION
**Pull request by davidanthoff**
Fixes #12.

### CODE REVIEW

**Comment by bicycle1885** [comment]
Thank you very much! What is the reason for BinaryProvider.jl not to work?

**Comment by davidanthoff** [comment]
@bicycle1885 I think this is now ready to be merged! Would be great if you could then also tag a release, I hope to get Parquet.jl working on Windows and having a tagged version of Snappy.jl would be the next step for that.

For now the snappy binaries are hosted at https://github.com/davidanthoff/SnappyBuilder. We could move the repo to your account, if you want to have all the involved things under your account? It is a bit tricky to setup the travis authentication, so we could also just leave it under my account for now, given that everything works. I'd be happy to maintain it there.

**Comment by davidanthoff** [comment]
@bicycle1885 Bump, any chance you could merge this and tag a new release? I have a whole set of other things that I'd like to move forward that all depend on this :) Thanks!

**Comment by bicycle1885** [comment]
Thank you. I'll take a look today.

**Comment by bicycle1885** [comment]
@davidanthoff Looks perfect! Thank you, again!. I've tagged Snappy.jl 0.2, so please wait for https://github.com/JuliaLang/METADATA.jl/pull/12668.

**Comment by davidanthoff** [comment]
Thanks!

**Pull request merged**
