### PR TITLE
Update to Julia 1.3+, use Snappy_jll to provide binaries

### PR DESCRIPTION
**Pull request by staticfloat**
This allows for am uch wider set of supported platforms, through use of
the `Snappy_jll` package.

### CODE REVIEW

**Comment by staticfloat** [comment]
@bicycle1885 this was a very easy upgrade; it vastly expands the number of platforms supported by this package and should future-proof it for a while yet.

**Comment by calebwin** [comment]
@bicycle1885 Can we get this merged?

**Comment by twadleigh** [comment]
:bump:

**Comment by ExpandingMan** [comment]
I actually just did this myself before realizing this PR existed.

Can we please get this merged?  I have another package that will depend on this that will eventually need to get registered.  If this does not get merged sometime before then I'm  going to have to just fork it.

**Comment by artinmg** [comment]
At the moment it is not possible to compile Parquet.jl on M1 Macs because Snappy.jl won't compile. Hope this can get merged soon!

**Comment by ExpandingMan** [comment]
The maintainers seem to be MIA.  If this can't get merged by the time I register Parquet2.jl I will fork it.

**Pull request merged**
